- id: check-django-migration-locks
  name: Check Django Migration Locks
  description: 'BLOCKS commit if Django migrations lock 2+ large tables simultaneously'
  entry: check-migration-locks
  language: python
  types: [python]
  args: [
    --min-tables, '2',
    --strict
  ]
  files: ^.*/migrations/.*\.py$
  fail_fast: true  # ⚠️ Stop on first error
